name: "Upload"
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: blitz
    - shell: sh
      env: # Or as an environment variable
        WWW_USER: ${{ secrets.WWW_USER }}
        WWW_PASS: ${{ secrets.WWW_PASS }}
        WWW_HOST: ${{ secrets.WWW_HOST }}
      run: |
        nix-build ./nix/release.nix -A upload
        ./result/bin/upload "$WWW_USER" "$WWW_PASS" "$WWW_HOST"
